### PR TITLE
Fixes for 34 and 99

### PR DESCRIPTION
**Pull request by lunacodes**
Fixes for: 
* #34 - Change Gitter to Matrix on Community
* #99 - Correct <nav> tag indentation. Replace Feature box <h3> tags with <a> tags, to avoid unnecessary anchor link.

### CODE REVIEW

**Review by mr-c — APPROVED** [review]

**Comment by mr-c** [comment]
Screenshot_20220303-080254
Can this icon be changed to Matrix's and the link updated as well?

**Comment by lunacodes** [comment]
> Can this icon be changed to Matrix's and the link updated as well?

@mr-c What's the correct icon for this? https://en.wikipedia.org/wiki/File:Matrix_icon.svg or https://matrix.to/images/chat-icon-864347221.svg

**Comment by mr-c** [comment]
> > Can this icon be changed to Matrix's and the link updated as well?
> 
> @mr-c What's the correct icon for this? https://en.wikipedia.org/wiki/File:Matrix_icon.svg or https://matrix.to/images/chat-icon-864347221.svg

The first one. Thank you!

**Comment by lunacodes** [comment]
Ok - I'll have that up on Monday

**Comment by lunacodes** [comment]
Sorry, I didn't get to this yet. I've made a note for myself to finish it up this Monday

**Pull request merged**
