### PR TITLE
Linkchecking ; fix URLs

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by mr-c** [comment]
@lunacodes There are some content updates in this PR ; can you port them over to the new website?

**Comment by lunacodes** [comment]
> @lunacodes There are some content updates in this PR ; can you port them over to the new website?

@mr-c Just want to make sure that removing Maxim's info in [a085b1](https://github.com/common-workflow-language/cwl-website/pull/86/commits/a085b15b339d07e545a765e811e949aea6927306) is intentional - since they'd be the only person on the page, without contact info listed.

Otherwise, the changes are good to go, and I'll push them once you confirm.

**Comment by lunacodes** [comment]
Also just want to check what the reason for switching the Open Stand icon from local to GitHub in [fcf938](https://github.com/common-workflow-language/cwl-website/pull/86/commits/fcf9383c198df95a9df9333bca47c8422d237007) is, and if there's a reason to copy it over.

**Comment by mr-c** [comment]
> > @lunacodes There are some content updates in this PR ; can you port them over to the new website?
> 
> @mr-c Just want to make sure that removing Maxim's info in [a085b15](https://github.com/common-workflow-language/cwl-website/pull/86/commits/a085b15b339d07e545a765e811e949aea6927306) is intentional - since they'd be the only person on the page, without contact info listed.
> 
> Otherwise, the changes are good to go, and I'll push them once you confirm.
> 

That's correct

**Comment by mr-c** [comment]
> Also just want to check what the reason for switching the Open Stand icon from local to GitHub in [fcf9383](https://github.com/common-workflow-language/cwl-website/pull/86/commits/fcf9383c198df95a9df9333bca47c8422d237007) is, and if there's a reason to copy it over.
The path was a bit weird, and it was the last live to fix for local checking of links

**Comment by swzCuroverse** [comment]
Not sure where my comment went - but I don't like this.  The boxes are supposed to be highlights of why CWL is great and contain 1 statement.  The box is formatted incorrectly - and doesn't follow that pattern.  Additionally, the content moved doesn't fit the flow of the page and isn't in the correct format and looks odd.  I would suggest either moving it back OR rewriting the box and at the minimium making it look like everything else.

**Pull request merged**
