### PR TITLE
kramdown (~> 2.1)

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by mr-c** [comment]
Downloading kramdown-parser-gfm-1.1.0 revealed dependencies not in the API or
1:29:04 PM: the lockfile (kramdown (~> 2.0)).
1:29:04 PM: Either installing with `--full-index` or running `bundle update
kramdown-parser-gfm` should fix the problem.
1:29:04 PM: Error during gem install

**Comment by mr-c** [comment]
@lunacodes  can you look at https://app.netlify.com/sites/cwl-website/deploys/609bbdc3bb703600071e5acb ?

**Comment by mrc** [comment]
@lunacodes you meant to tag @mr-c I think, I'm not associated with this project

**Comment by lunacodes** [comment]
Ahh sry about that!!

**Comment by mr-c** [comment]
> @mr-c c can you add `--trace` to the command? I gave it a look, but it's not really showing anything helpful.

@lunacodes can you take over this branch/PR directly?

**Pull request merged**
